services:

#Servicio autogenerado por Pcabreus Generator 
    post.form:
        class: Positibe\Bundle\NewsBundle\Form\Type\PostFormType
        tags:
            - { name: form.type, alias: positibe_post }

#Servicio autogenerado por Pcabreus Generator 
    post_tag.form:
        class: Positibe\Bundle\NewsBundle\Form\Type\TagFormType
        arguments: [%locales%]
        tags:
            - { name: form.type, alias: positibe_post_tag }

#Servicio autogenerado por Pcabreus Generator 
    post_collection.form:
        class: Positibe\Bundle\NewsBundle\Form\Type\CollectionFormType
        arguments: [%locales%]
        tags:
            - { name: form.type, alias: positibe_post_collection }

#Servicio autogenerado por Pcabreus Generator 
    post_comment.form:
        class: Positibe\Bundle\NewsBundle\Form\Type\CommentFormType
        arguments: [@security.authorization_checker]
        tags:
            - { name: form.type, alias: positibe_post_comment }