sylius_resource:
    resources:

#Servicio autogenerado por Pcabreus Generator 
        positibe.post:
            driver: doctrine/orm
            templates: PositibeNewsBundle:Post
            classes:
                model: Positibe\Bundle\NewsBundle\Entity\Post
                controller: Positibe\Bundle\NewsBundle\Controller\PostController
                repository: Positibe\Bundle\NewsBundle\Entity\PostRepository


#Servicio autogenerado por Pcabreus Generator 
        positibe.post_tag:
            driver: doctrine/orm
            templates: PositibeNewsBundle:Tag
            classes:
                model: Positibe\Bundle\NewsBundle\Entity\Tag
                controller: Positibe\Bundle\CmfBundle\Controller\TranslatableController
                repository: Positibe\Bundle\NewsBundle\Entity\TagRepository


#Servicio autogenerado por Pcabreus Generator 
        positibe.post_collection:
            driver: doctrine/orm
            templates: PositibeNewsBundle:Collection
            classes:
                model: Positibe\Bundle\NewsBundle\Entity\Collection
                controller: Positibe\Bundle\CmfBundle\Controller\TranslatableController
                repository: Positibe\Bundle\NewsBundle\Entity\CollectionRepository



#Servicio autogenerado por Pcabreus Generator 
        positibe.post_comment:
            driver: doctrine/orm
            templates: PositibeNewsBundle:Comment
            classes:
                model: Positibe\Bundle\NewsBundle\Entity\Comment
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\NewsBundle\Entity\CommentRepository
