<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class CollectionFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 */
class CollectionFormType extends AbstractType
{
    private $locales;

    public function __construct($locales)
    {
        $this->locales = $locales;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add(
            'name',
            null,
            array(
              'label' => 'Nombre'
            )
          )
          ->add(
            'description',
            null,
            array(
              'label' => 'Descripción'
            )
          )
          ->add(
            'locale',
            'choice',
            array(
              'label' => 'Idioma',
              'choices' => array_combine($this->locales, $this->locales)
            )
          )
          /*->add(
            'enabled',
            null,
            array(
              'label' => 'Habilitado'
            )
          )*/;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
          array(
            'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Collection'
          )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'positibe_post_collection';
    }
}
