<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class FrontendCommentFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 *
 * @author Pedro Carlos Abreu <pcabreus@gmail.com>
 */
class FrontendCommentFormType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(
            FormEvents::POST_SET_DATA,
            function (FormEvent $event) {
                $type = null;
                if ($event->getData()) {
                    $type = HiddenType::class;
                };

                $event->getForm()
                    ->add(
                        'name',
                        $type,
                        array(
                            'label' => 'post_comment.form.name_label',
                        )
                    )->add(
                        'email',
                        $type,
                        array(
                            'label' => 'post_comment.form.email_label',
                        )
                    )->add(
                        'url',
                        $type,
                        array(
                            'label' => 'post_comment.form.url_label',
                        )
                    );
            }
        );

        $builder
            ->add(
                'message',
                null,
                array(
                    'label' => 'post_comment.form.message_label',
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Comment',
            )
        );
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'post_comment';
    }
}
