<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class PostFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 */
class PostFormType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add(
            'featured',
            null,
            array(
              'label' => 'Noticia destacada',
              'required' => false,
            )
          )
          ->add(
            'tags',
            'positibe_tag',
            array(
              'label' => 'Etiquetas',
              'class_name' => 'Positibe\Bundle\NewsBundle\Entity\Tag'
            )
          )
          ->add(
            'collections',
            null,
            array(
              'label' => 'Categoría',
              'attr' => array(
//                                  'class' => 'chosen-select'
              ),
              'empty_value' => '-- Eliga una categoría --',
              'multiple' => true,
              'expanded' => true
            )
          );
    }

    public function getParent()
    {
        return 'positibe_abstract_page';
    }


    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
          array(
            'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Post'
          )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'positibe_post';
    }
}
