<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class TagFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 */
class TagFormType extends AbstractType
{

    private $locales;

    public function __construct($locales)
    {
        $this->locales = $locales;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add(
            'name',
            null,
            array(
              'label' => 'Nombre'
            )
          )->add(
            'locale',
            'choice',
            array(
              'label' => 'Idioma',
              'choices' => array_combine($this->locales, $this->locales)
            )
          )/*
          ->add(
            'enabled',
            null,
            array(
              'label' => 'Habilitada'
            )
          )*/
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
          array(
            'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Tag'
          )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'positibe_post_tag';
    }
}
