positibe_news_admin_news_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: positibe_news.controller.news:createAction
        _sylius:
            template: PositibeNewsBundle:Admin/News:create.html.twig
            redirect:
                route: positibe_news_admin_news_show
                parameters: {slug: resource.slug}

positibe_news_admin_news_show:
    path: /{slug}
    methods: [GET]
    defaults:
        _controller: positibe_news.controller.news:showAction
        _sylius:
            template: PositibeNewsBundle:Admin/News:show.html.twig
            criteria:
                slug: $slug

positibe_news_admin_news_update:
    path: /{slug}/edit
    methods: [GET, PUT]
    defaults:
        _controller: positibe_news.controller.news:updateAction
        _sylius:
            template: PositibeNewsBundle:Admin/News:update.html.twig
            criteria:
                slug: $slug
            redirect:
                route: positibe_news_admin_news_show
                parameters: {slug: resource.slug}

positibe_news_admin_news_delete:
    path: /{slug}
    methods: [DELETE]
    defaults:
        _controller: positibe_news.controller.news:deleteAction
        _sylius:
            criteria:
                slug: $slug
            redirect:
                route: positibe_news_admin_news_index
                parameters: {}

positibe_news_admin_news_index:
    path: /
    methods: [GET]
    defaults:
        _controller: positibe_news.controller.news:indexAction
        _sylius:
            template: PositibeNewsBundle:Admin/News:index.html.twig
            sortable: true
            filterable: true
            method: createFilterPaginator
