positibe_post_comment_index:
    path: /post-comments
    defaults:
        _controller: "positibe.controller.post_comment:indexAction"
        _sylius:
            template: PositibeNewsBundle:Comment:index.html.twig
            sortable: true
            sorting:
                updatedAt: DESC

positibe_post_comment_crud:
    resource: |
        alias: positibe.post_comment
        templates: PositibeNewsBundle:Comment
        except: ["create", "index"]
        redirect: update
    type: sylius.resource

positibe_post_comment_create:
    path: /post-comments/{postName}/new
    methods: [GET, POST]
    defaults:
        _controller: positibe.controller.post_comment:createAction
        _sylius:
            template: PositibeNewsBundle:Comment:create.html.twig
            factory:
                method: createByPostName
                arguments: [$postName]
            redirect:
                route: positibe_post_comment_update
                parameters: {id: resource.id}

positibe_post_comment_transition:
    path: /post-comments/{id}/transition
    methods: POST
    defaults:
        _controller: positibe.controller.post_comment:applyTransitionAction